const ADD_PRODUCT = 'ADD_PRODUCT';
const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const SELECT_PRODUCT = 'SELECT_PRODUCT';
const UPDATE_PRODUCT = 'UPADTE_PRODUCT';

export { ADD_PRODUCT, REMOVE_PRODUCT, SELECT_PRODUCT, UPDATE_PRODUCT };